version: '3'
services:
  content-service-app:
    build:
      context: .
    ports:
      - '3008:3008'
    container_name: content-service
    restart: always
    networks:
      - ai-network
    environment:
      - MONGODB_URL=mongodb://MONGO:27017/all-content-respository
      - ALL_LC_API_URL=https://lct-api.theall.ai/v1/language/tools/wordComplexity/
      - SERVER_URL=https://www.learnerai-dev.theall.ai/content-service/
      - ALL_TEXT_EVAL_URL=https://www.learnerai-dev.theall.ai/text-eval/
networks:
  ai-network:
    driver: bridge
